### ISSUE TITLE
Got exception on Android 11

### ISSUE THREAD

**Issue by finchatticus** [nedimf/maildroid#32]
**To Reproduce**
Use Android 11
Version of lib: v0.0.6-release

trying send email using following code:

```kotlin 

sendEmail {
            smtp("smtp.gmail.com")
            smtpUsername("....")
            smtpPassword("....")
            port("465")
            type(MaildroidXType.PLAIN)
            to("....@gmail.com")
            from("Test")
            subject("Test")
            body("Test")
            attachment(path to file)
            onCompleteCallback(object : MaildroidX.onCompleteCallback {
                override val timeout = 20_000L

                override fun onSuccess() {
                    
                }

                override fun onFail(errorMessage: String) {
                    
                }

            })
        }
```
**See error**:
```
java.lang.VerifyError: Rejecting class com.sun.mail.handlers.text_plain that attempts to sub-type erroneous class com.sun.mail.handlers.handler_base (declaration of 'com.sun.mail.handlers.text_plain' appears in /data/app/~~2p-u-SKN4fRsh6MWdSC7nQ==/***.***.***-z7AKAGLybnYB-JoQrwg_NQ==/base.apk!classes3.dex)
        at java.lang.Class.newInstance(Native Method)
        at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:631)
        at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:585)
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:627)
        at javax.activation.DataHandler.writeTo(DataHandler.java:329)
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:340)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1575)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1172)
        at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:522)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1533)
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2271)
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2231)
        at javax.mail.Transport.send(Transport.java:123)
        at co.nedim.maildroidx.MaildroidX$Builder$send$1.run(MaildroidX.kt:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.VerifyError: Verifier rejected class com.sun.mail.handlers.handler_base: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors() failed to verify: java.awt.datatransfer.DataFlavor[] com.sun.mail.handlers.handler_base.getTransferDataFlavors(): [0x4]  can't resolve returned type 'Unresolved Reference: java.awt.datatransfer.DataFlavor[]' or 'Reference: javax.activation.ActivationDataFlavor[]' (declaration of 'com.sun.mail.handlers.handler_base' appears in /data/app/~~2p-u-SKN4fRsh6MWdSC7nQ==/***.***.***-z7AKAGLybnYB-JoQrwg_NQ==/base.apk!classes3.dex)
        at java.lang.Class.newInstance(Native Method) 
        at javax.activation.MailcapCommandMap.getDataContentHandler(MailcapCommandMap.java:631) 
        at javax.activation.MailcapCommandMap.createDataContentHandler(MailcapCommandMap.java:585) 
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:627) 
        at javax.activation.DataHandler.writeTo(DataHandler.java:329) 
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:340) 
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1575) 
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1172) 
        at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:522) 
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1533) 
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2271) 
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2231) 
        at javax.mail.Transport.send(Transport.java:123) 
        at co.nedim.maildroidx.MaildroidX$Builder$send$1.run(MaildroidX.kt:262) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
2021-02-07 18:06:16.675 5565-5615/***.***.*** E/CrashlyticsCore: Error occurred sending report com.crashlytics.android.core.SessionReport@46dec0b
```

**Comment by nedimf** [comment]
Issue seems to be with JavaMail [have look here](https://github.com/eclipse-ee4j/mail/issues/516).
Can you please check the proguard and add these lines, this should mitigate the issue

```
-keep class com.sun.mail.imap.** {;}
-keep class com.sun.mail.smtp.** {;}
-keep class com.sun.mail.handlers.** {;}
-keep class javax.activation.** {;}

-dontwarn com.sun.mail.**
-dontwarn org.apache.harmony.awt.**
-dontwarn javax.security.sasl.**
-dontwarn java.awt.**
-dontwarn java.beans.**
```
@finchatticus

**Comment by x64Dev** [comment]
@nedimf I'm facing the issue on debug (proguard isn't apply on debug builds).

**Comment by nedimf** [comment]
Alright, issue is in JavaMail API, I'll try to make separate release with different JavaMail version, specifically for Android 11.

**Comment by nedimf** [comment]
I have changed JavaMail API to release 1.6.3 then ran a test on Android 11. Everything worked on my side. Let me know if issue is resolved for you guys @finchatticus @x64Dev

**Comment by nedimf** [comment]
Please try v0.0.7-release as fix for this issue

**Comment by thetaprimeprime** [comment]
v0.0.8-release also has this issue
